name: Examples

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  examples:
    name: Run Examples
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        examples:
          - psbt
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Rust
        run: rustup show

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-on-failure: true

      - name: Run the examples
        run: cargo run --example ${{ matrix.examples }}
